UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=1;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=2;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=3;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=4;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=5;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=6;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=7;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=8;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=9;
UPDATE `task1` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=10;
update total_points set task1=null where FK_studentId=2106091;

UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=1;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=2;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=3;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=4;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=5;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=6;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=7;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=8;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=9;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=10;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=11;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=12;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=13;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=14;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=15;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=16;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=17;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=18;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=19;
UPDATE `task2` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=20;
update total_points set task2=null where FK_studentId=2106091;

UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=1;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=2;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=3;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=4;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=5;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=6;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=7;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=8;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=9;
UPDATE `task3` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=10;
update total_points set task3=null where FK_studentId=2106091;

UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=1;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=2;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=3;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=4;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=5;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=6;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=7;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=8;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=9;
UPDATE `task4` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=10;
update total_points set task4=null where FK_studentId=2106091;

UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=1;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=2;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=3;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=4;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=5;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=6;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=7;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=8;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=9;
UPDATE `task5` SET `inserted_value`=null,`evaluation`=null WHERE FK_studentId=2106091 and `exercise_number`=10;
update total_points set task5=null where FK_studentId=2106091;